# Generated by Django 5.2.17 on 2026-08-18 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('azienda', models.CharField(blank=True, max_length=120)),
                ('sito', models.CharField(blank=True, help_text='Sito web da cui proviene il contatto.', max_length=120)),
                ('messaggio', models.TextField(blank=True)),
                ('dati_extra', models.JSONField(blank=True, default=dict, help_text='Eventuali campi aggiuntivi inviati dal form del sito.')),
                ('stato', models.CharField(choices=[('nuovo', 'Nuovo'), ('contattato', 'Contattato'), ('archiviato', 'Archiviato')], default='nuovo', max_length=20)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('assegnato_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assegnati', to=settings.AUTH_USER_MODEL, verbose_name='Assegnato a')),
            ],
            options={
                'verbose_name': 'contatto',
                'verbose_name_plural': 'contatti',
                'ordering': ['-creato_il'],
            },
        ),
    ]
