# Generated by Django 5.2.17 on 2026-08-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='consenso_dati',
            field=models.BooleanField(default=False, help_text='Autorizzazione acquisita dal form del sito (GDPR).', verbose_name='Consenso al trattamento dei dati personali'),
        ),
        migrations.AddField(
            model_name='lead',
            name='consenso_dati_il',
            field=models.DateTimeField(blank=True, help_text='Compilata automaticamente alla ricezione del consenso.', null=True, verbose_name='Data del consenso'),
        ),
    ]
