# Generated by Django 5.2.17 on 2026-08-18 10:28

import django.db.models.deletion
import leads.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_consenso_dati_lead_consenso_dati_il'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('dominio', models.CharField(blank=True, help_text='Es. www.calcioolgiate.it — usato per valorizzare lead.sito.', max_length=200)),
                ('ingest_token', leads.fields.EncryptedCharField(blank=True, editable=True, help_text='Token con cui il sito autentica le chiamate a /ingest/ (header X-Ingest-Token). Cifrato a riposo.', null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'sito',
                'verbose_name_plural': 'siti',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='sorgente',
            field=models.ForeignKey(blank=True, help_text='Sito configurato da cui è arrivato il contatto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='leads.sito'),
        ),
        migrations.CreateModel(
            name='CampoSito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('etichetta', models.CharField(blank=True, max_length=120)),
                ('tipo', models.CharField(choices=[('testo', 'Testo'), ('testo_lungo', 'Testo lungo'), ('email', 'Email'), ('telefono', 'Telefono'), ('data', 'Data'), ('numero', 'Numero'), ('checkbox', 'Checkbox')], default='testo', max_length=20)),
                ('destinazione', models.CharField(choices=[('nome', 'Nome'), ('email', 'Email'), ('telefono', 'Telefono'), ('azienda', 'Azienda'), ('messaggio', 'Messaggio'), ('consenso', 'Consenso dati personali'), ('extra', 'Extra (solo archivio)')], default='extra', max_length=20)),
                ('obbligatorio', models.BooleanField(default=False)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('sito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campi', to='leads.sito')),
            ],
            options={
                'verbose_name': 'campo del sito',
                'verbose_name_plural': 'campi dei siti',
                'ordering': ['sito', 'ordine', 'key'],
                'unique_together': {('sito', 'key')},
            },
        ),
    ]
