# Generated by Django 5.2.17 on 2026-08-19 13:25

import django.db.models.deletion
import leads.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_sito_lead_sorgente_camposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='risposta_automatica_errore',
            field=models.CharField(blank=True, max_length=500, verbose_name='Errore risposta automatica'),
        ),
        migrations.AddField(
            model_name='lead',
            name='risposta_automatica_inviata_il',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Risposta automatica inviata il'),
        ),
        migrations.CreateModel(
            name='RispostaAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivo', models.BooleanField(default=False, help_text='Se disattivata, la configurazione resta salvata ma nessuna email viene inviata.', verbose_name='Risposta automatica attiva')),
                ('mittente_nome', models.CharField(blank=True, max_length=120)),
                ('mittente_email', models.EmailField(max_length=254, verbose_name='Email mittente')),
                ('oggetto', models.CharField(default='Grazie per averci contattato', max_length=255)),
                ('corpo_html', models.TextField(blank=True, help_text='Placeholder disponibili: {{nome}}, {{email}}, {{telefono}}, {{azienda}}, {{messaggio}}, {{sito}}.', verbose_name='Corpo email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='risposte_automatiche/loghi/', verbose_name='Logo del brand')),
                ('firma_html', models.TextField(blank=True, verbose_name='Firma email')),
                ('smtp_host', models.CharField(blank=True, max_length=255, verbose_name='Host SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='Porta SMTP')),
                ('smtp_user', models.CharField(blank=True, max_length=255, verbose_name='Utente SMTP')),
                ('smtp_password', leads.fields.EncryptedCharField(blank=True, editable=True, null=True, verbose_name='Password SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Usa STARTTLS')),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('sito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risposta_automatica', to='leads.sito')),
            ],
            options={
                'verbose_name': 'risposta automatica',
                'verbose_name_plural': 'risposte automatiche',
            },
        ),
    ]
